require("tomasantunes.plugins-setup")
require("tomasantunes.core.options")
require("tomasantunes.core.keymaps")
require("tomasantunes.core.colorscheme")
require("tomasantunes.plugins.comment")
require("tomasantunes.plugins.nvim-tree")
require("tomasantunes.plugins.lualine")
require("tomasantunes.plugins.telescope")
require("tomasantunes.plugins.nvim-cmp")
require("tomasantunes.plugins.lsp.mason")
-- require("tomasantunes.plugins.lsp.lspconfig")
-- require("tomasantunes.plugins.lsp.lspsaga")
-- require("tomasantunes.plugins.lsp.null-ls")
require("tomasantunes.plugins.autopairs")
require("tomasantunes.plugins.treesitter")
require("tomasantunes.plugins.gitsigns")
require("tomasantunes.plugins.lsp.lsp")
